### ISSUE TITLE
Clarify what the checkbox "delete" does?

### ISSUE THREAD

**Issue by numeroteca** [cadaveresinmob/c_inmobiliarios#25]
In the edit screen, under the Address section there is a checkbox "delete" and the clarification "Check this box to delete this location". Is it deleting the corpse or just the address when saving .
How is that related to the "clear button"?

**Comment by ccamara** [comment]
"Limpiar" button only deletes the addresses' fields (city, street, address...), but it won't delete anything else.

Delete checkbox would delete a complete address (including coordinates). this would only make sense in case of having multiple addresses per node (which is not the case).

This makes me think that we may want to document the process (I created an issue for that: #26)

Feel free to close the issue if we are done with it.

**Comment by numeroteca** [comment]
I think it needs a bit of clarification to inform that you are not actually deleting the "copse" when checking that box but the coordinates. What'd you want to do that? 
The problematic thing to me is to have a checkbox for doing this. Can't be a button?

**Comment by ccamara** [comment]
Although you are right that it is confusing and it may need to be removed, I will mark this as won't fix since it is not easy to fix* and I don't think it is prioritary, as nothing bad can happen (at this moment there's no possibility to save changes without any georreference, and ultimately we could restore that from history)

* In order to fix that I would need to study the getlocations module, which is quite complex, try to find where does the checkbox come from and then study how to hide it (which I honestly don't know how to do it yet). Additionally, since it is a contributed module, I should create a patch and submit it to module mantainer, and/or keep it in order to apply it whenever we decide to update its version (and pray for that there hasn't been any change on those lines so it can be applied gracefuly).
