### ISSUE TITLE
[TS] New Drupal field needed: urban corpse status

### ISSUE THREAD

**Issue by skotperez** [cadaveresinmob/c_inmobiliarios#27]
This field is needed to tag urban corpses as "adoptado" or "desenterrado". In the future it could be more statuses.

**Comment by ccamara** [comment]
Done.

**Comment by numeroteca** [comment]
We can use it for corpses that stop being corpses, because they are being used.
For me they are:

- **desenterrado**: cuando del cadáver solo se sabe localización y una somera desictipción (si la hay)
- **adoptado**: cualquier cadáver con algo de información. Podemos fijar unos mínimos, como hacemos ahora o no (los campos del formulario de Adopta un cadáver).
- **vivo**: cuando el cadáver deja de serlo. Se descubre que ya no es un cadáver o qu era un falso positivo.

**Comment by skotperez** [comment]
Ah ! Muy bueno el concepto vivo, claro qué sí.

Quizás llamarlo mejor resucitado? :)

**Comment by numeroteca** [comment]
Resucitado mejor, sí.

**Comment by ccamara** [comment]
:+1:  to the proposal.

At this moment I created a field that reads taxonomies (categories) from a closed vocabulary. It is as easy as adding a new term (you could do it by yourselves, if I had explained how to do that ;) ) In fact I have created the new term and you'll be able to see it on the new website.

Unfortunately, as I was writing this issue #34 I was thinking that it may be necessary to change the approach and use [flags](http://dgo.to/flags) instead of a taxonomy field. In this way regular users won't be able to change the status and we could update the status Desenterrados -> Adoptados -> Resucitados programatically. 

I'm reopening this issue as I want to know about your opinon and test both approaches, since it will be now or never ;)

**Comment by ccamara** [comment]
We can't use flags as they only have two status: either on or off. Using taxonomy is the right approach, then.

**Comment by numeroteca** [comment]
Creo que tenemos que tenr claro las diferencias de unos estados y otros:

- desenterrado: un lugar del que se sabe poco. Sólo hay lat/long y un breve comentario
- adoptado: añade al desenterrado más datos como nombre, principales taxonomías... ¿cual es el mínimo para considerarlo adoptado?
- resucitado: ha dejado de ser cadaver por que era un falso positivo o porque se ha puesto en uso.

Por defecto que sea por categoría, que cualquier usuario pueda cambiarlo. La idea es no poner barreras antes de tener usuarios o trolls.

**Comment by ccamara** [comment]
sí, tengo claras las diferencias. Mi idea es que como cambiar el estado de desenterrado a adoptado es manual, puede que se olvide de actualizar. De ahí que propusiera (en la issue #34) estudiar la opción de que cuando un determinado número de campos estuvieran rellenados, el estado (categoría) cambiase de forma automática. Aunque eso no niega que pueda volver a cambiarse de nuevo. De todos modos, no es prioritario, solo lo comentaba aquí porque quería estudiar las dos opciones para que una no nos condicionase en el futuro.
