### ISSUE TITLE
Move contributing.md to a wiki page

### ISSUE THREAD

**Issue by numeroteca** [cadaveresinmob/c_inmobiliarios#36]
It will be easier to contribute!

**Comment by ccamara** [comment]
I was asking myself the same question when deciding wether create a wiki page or a file within the repository. 

Finally I decided to use a file called `contributing.md` within the repo because of this reasons:

* It is a broadly used convention to add such a file in the repo, as most open source projects have one.
* If githubs detects a file like that it adds a short message before creating an issue or a pull request linking to it, which I think is very handy  (see screenshot or read more on [this article on github](https://help.github.com/articles/setting-guidelines-for-repository-contributors/))
![new issue 2016-02-19 20-42-26](https://cloud.githubusercontent.com/assets/706549/13187076/69247964-d749-11e5-938d-7ab1cf1738f2.png)

However, your message have made myself ask the same question, and after your message I have been looking for more reccomendations on which method is recommended and I didn't find anything like that. Maybe the most similar reference is [this document from github](https://guides.github.com/activities/contributing-to-open-source/) in which explains how to contribute in general and how open source projects can be organized (we should take that document as a reference! it's very well written and explained!). They say the following:

> **Contributing**
>
>Projects and project maintainers vary, so the best way to contribute will also vary. Keep your eye open for a doc labeled CONTRIBUTING. Contributing docs detail the specifics about how a project’s maintainer would like to see patches or features contributed. This can include what tests to write, code syntax style or areas to focus on for patches.
>
> [...]
>
>  **Documentation and Wikis**
>
>Many larger projects go beyond a readme to give instructions for how people can use their project. In such cases you’ll often find a link to another file or a folder named ‘docs’ in the repository.

I also found [this discussion on another projec](https://github.com/hypatia-software-org/hypatia-engine/issues/76)t and after discussing how to have two automated copies of the same version (one within the repo and another as a wiki -which I believe technically speaking is another git repository) they decided to have two different copies.

After these two links I think it may be a good option to have two versions with different content (one as a file, another as a wiki) as they may be addressed to different people (repo +- developers/coders, wiki = all publics).

What do you think?

**Comment by ccamara** [comment]
PS: although it is really easy to contribute to a wiki, it is not less difficult to contribute to a markdown file from github's interface, in fact, both use the same editor.

**Comment by numeroteca** [comment]
Interesting references. I was not aware about these debates.
Let's keep it simple and in one place. Since it's possible to edit the `contributing.md` with the github interface there is no need to open the wiki, I'd say.

**Comment by ccamara** [comment]
Ok, so let's keep it there. Closing the issue.
